services:
    _defaults:
        autowire: false
        autoconfigure: false

    Sylius\Calendar\Tests\Provider\CalendarInterface:
        class: Sylius\Calendar\Tests\Behat\Provider\FakeCalendar
        arguments:
            - "%kernel.project_dir%"

    Sylius\Calendar\Tests\Behat\Context\Domain\CalendarContext:
        public: true
        arguments:
            - '@Sylius\Calendar\Tests\Provider\CalendarInterface'

    Sylius\Calendar\Tests\Behat\Context\Setup\CalendarContext:
        public: true
        arguments:
            - "%kernel.project_dir%"
