name: Build

on:
    push: ~
    pull_request: ~
    release:
        types: [ created ]
    schedule:
        -   cron: "0 1 * * 6" # Run at 1am every Saturday

jobs:
    tests:
        runs-on: ubuntu-latest

        name: PHP ${{ matrix.php }}

        strategy:
            fail-fast: false
            matrix:
                php: ["8.0"]

        steps:
            -
                uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    coverage: none

            -
                name: Install PHP dependencies
                run: composer install --no-interaction

            -
                name: Run PHPSpec
                run: vendor/bin/phpspec run --ansi -f progress --no-interaction
